#!/bin/bash
#
#
# ovirt-agent       startup script for ovirt-agent
#
# chkconfig: - 97 03
# description: ovirt-agent provides the QMF API for ovirt VM manager.
#

[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails

export RAILS_ENV="${RAILS_ENV:-production}"

DAEMON=/usr/share/ovirt-server/ovirt-agent/ovirt-agent.rb
AGENT_LOCKFILE="${AGENT_LOCKFILE:-/var/lock/subsys/ovirt-agent }"

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-agent: "
    daemon $DAEMON
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        touch  $AGENT_LOCKFILE
    fi
}

stop() {
    echo -n "Shutting down ovirt-agent: "
    killproc ovirt-agent.rb
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm  $AGENT_LOCKFILE
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-agent {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
