#!/bin/bash
#
#
# ovirt-agent       startup script for ovirt-agent
#
# chkconfig: - 97 03
# description: ovirt-agent provides the QMF API for ovirt VM manager.
#

[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails

export RAILS_ENV="${RAILS_ENV:-production}"

DAEMON=/usr/share/ovirt-server/ovirt-agent/ovirt-agent.rb

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-agent: "
    daemon $DAEMON
    RETVAL=$?
    echo
}

stop() {
    echo -n "Shutting down ovirt-agent: "
    killproc ovirt-agent.rb
    RETVAL=$?
    echo
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-agent {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
