#!/bin/bash
#
#
# ovirt-host-browser       startup script for ovirt-host-browser
#
# chkconfig: - 97 03
# description: ovirt-host-browser is an essential component of the \
#    ovirt VM manager.
#

[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails

export RAILS_ENV="${RAILS_ENV:-production}"

DAEMON=/usr/share/ovirt-server/host-browser/host-browser.rb
HOST_BROWSER_LOCKFILE="${HOST_BROWSER_LOCKFILE:-/var/lock/subsys/ovirt-host-browser }"

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-host-browser: "
    daemon $DAEMON
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        touch  $HOST_BROWSER_LOCKFILE
    fi
}

stop() {
    echo -n "Shutting down ovirt-host-browser: "
    killproc host-browser.rb
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm  $HOST_BROWSER_LOCKFILE
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-host-browser {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
