#!/bin/bash
#
#
# ovirt-host-register       startup script for ovirt-host-register
#
# chkconfig: - 97 03
# description: ovirt-host-register is an essential component of the \
#    ovirt VM manager, handling the bookkeeping for hw nodes managed \
#    by the server.
#

[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails

export RAILS_ENV="${RAILS_ENV:-production}"

DAEMON=/usr/share/ovirt-server/host-browser/host-register.rb
HOST_REGISTER_LOCKFILE="${HOST_REGISTER_LOCKFILE:-/var/lock/subsys/ovirt-host-register }"

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-host-register: "
    daemon $DAEMON
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        touch  $HOST_REGISTER_LOCKFILE
    fi
}

stop() {
    echo -n "Shutting down ovirt-host-register: "
    killproc host-register.rb
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm  $HOST_REGISTER_LOCKFILE
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-host-register {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
