#!/bin/bash
#
#
# ovirt-taskomatic       startup script for ovirt-taskomatic
#
# chkconfig: - 97 03
# description: ovirt-taskomatic is an essential component of the \
#    ovirt VM manager.
#

[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails

export RAILS_ENV="${RAILS_ENV:-production}"
export COBBLER_YML="${COBBLER_YML:-/usr/share/ovirt-server/config/cobbler.yml}"

DAEMON=/usr/share/ovirt-server/task-omatic/taskomatic.rb
TASKOMATIC_LOCKFILE="${TASKOMATIC_LOCKFILE:-/var/lock/subsys/ovirt-taskomatic }"

. /etc/init.d/functions

start() {
    echo -n "Starting ovirt-taskomatic: "
    daemon $DAEMON
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        touch  $TASKOMATIC_LOCKFILE
    fi
}

stop() {
    echo -n "Shutting down ovirt-taskomatic: "
    killproc taskomatic.rb
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm  $TASKOMATIC_LOCKFILE
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    status)
	status $DAEMON
	RETVAL=$?
	;;
    *)
      echo "Usage: ovirt-taskomatic {start|stop|restart|status}"
      exit 1
  ;;
esac
exit $RETVAL
