#!/usr/bin/ruby

$: << '/usr/share/ovirt-server'
$: << '/usr/share/ovirt-server/dutils'

require 'dutils'

########################## retreive host from vm w/ specified name
$stdin.each{ |vmname| # get vm name from stdin
  begin
    vmname.chomp!  # remove the newline

    # specially handle 'anyterm' to just return
    # first host (for css/js/etc which aren't
    # vm dependent)
    if vmname == 'anyterm'
      puts Host.find(:first, :conditions => "state = 'available'").hostname
    else
      puts Vm.find(:first, :conditions => ['description = ?', vmname]).host.hostname
    end
  rescue Exception => e
      puts
  end

  $stdout.flush
}
