#!/bin/bash
[ -r /etc/sysconfig/ovirt-rails ] && . /etc/sysconfig/ovirt-rails
RAILS_ENV="${RAILS_ENV:-production}"
RAKEFILE=/usr/share/ovirt-server/Rakefile
MODELS="Host Vm IscsiStoragePool NfsStoragePool HardwarePool VmResourcePool"
RAILS_ENV=$RAILS_ENV rake -f $RAKEFILE xapian:update_index models="$MODELS"
